### ISSUE TITLE
feat(pwr): Refactor the application to only control the fan when the power meter is detected

### ISSUE THREAD

**Issue by edabe** [edabe/dreo-headwind#20]
An observed behavior is that the fan will start spinning the moment the heart rate monitor is detected. To improve on this, the application should look for the fitness equipment / power meter and only control the fan while the power meter is emitting data.

```
HR detected
- do nothing

PWR detected
- do nothing

PWR + HR detected
- control fan
```

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Update HeartRateMode class to include a flag for power meter activity and modify the adjustDreoProfile method to only control the fan when the power meter is active. Also update the main application logic to handle power meter detection and data.

You can review changes in this commit: https://github.com/jjyutm4532/edabe-dreo-headwind-20/commit/de9f61d1d54a1b0ef7d0d2221975283c69229348.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by edabe** [comment]
Wow... I'm impressed by @jjyutm4532 / latta.ai!
While the latta.ai solution seem to work, it kinds of breaks the boundaries by creating a power meter dependency inside `HeartRateMode` (I designed it to rely solely on heart rate).

However, it made me think that `HeartRateMode` should have an option to be externally enabled or disabled... hmm...
